//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech_Forum.DbAccessServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DbAccessServiceReference.IDbAccessService")]
    public interface IDbAccessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbAccessService/DoWork", ReplyAction="http://tempuri.org/IDbAccessService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbAccessService/DoWork", ReplyAction="http://tempuri.org/IDbAccessService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbAccessService/GetDomainList", ReplyAction="http://tempuri.org/IDbAccessService/GetDomainListResponse")]
        DbAccess.Domain_Table[] GetDomainList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbAccessService/GetDomainList", ReplyAction="http://tempuri.org/IDbAccessService/GetDomainListResponse")]
        System.Threading.Tasks.Task<DbAccess.Domain_Table[]> GetDomainListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbAccessService/GetTechforDomain", ReplyAction="http://tempuri.org/IDbAccessService/GetTechforDomainResponse")]
        DbAccess.Technology_Table[] GetTechforDomain(string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbAccessService/GetTechforDomain", ReplyAction="http://tempuri.org/IDbAccessService/GetTechforDomainResponse")]
        System.Threading.Tasks.Task<DbAccess.Technology_Table[]> GetTechforDomainAsync(string domain);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDbAccessServiceChannel : Tech_Forum.DbAccessServiceReference.IDbAccessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DbAccessServiceClient : System.ServiceModel.ClientBase<Tech_Forum.DbAccessServiceReference.IDbAccessService>, Tech_Forum.DbAccessServiceReference.IDbAccessService {
        
        public DbAccessServiceClient() {
        }
        
        public DbAccessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DbAccessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbAccessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbAccessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public DbAccess.Domain_Table[] GetDomainList() {
            return base.Channel.GetDomainList();
        }
        
        public System.Threading.Tasks.Task<DbAccess.Domain_Table[]> GetDomainListAsync() {
            return base.Channel.GetDomainListAsync();
        }
        
        public DbAccess.Technology_Table[] GetTechforDomain(string domain) {
            return base.Channel.GetTechforDomain(domain);
        }
        
        public System.Threading.Tasks.Task<DbAccess.Technology_Table[]> GetTechforDomainAsync(string domain) {
            return base.Channel.GetTechforDomainAsync(domain);
        }
    }
}
