//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech_Forum.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Domain_Table", Namespace="http://schemas.datacontract.org/2004/07/DbAccess")]
    [System.SerializableAttribute()]
    public partial class Domain_Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Technology_Table", Namespace="http://schemas.datacontract.org/2004/07/DbAccess")]
    [System.SerializableAttribute()]
    public partial class Technology_Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IDbAccessService")]
    public interface IDbAccessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbAccessService/DoWork", ReplyAction="http://tempuri.org/IDbAccessService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbAccessService/DoWork", ReplyAction="http://tempuri.org/IDbAccessService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbAccessService/GetDomainList", ReplyAction="http://tempuri.org/IDbAccessService/GetDomainListResponse")]
        Tech_Forum.ServiceReference.Domain_Table[] GetDomainList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbAccessService/GetDomainList", ReplyAction="http://tempuri.org/IDbAccessService/GetDomainListResponse")]
        System.Threading.Tasks.Task<Tech_Forum.ServiceReference.Domain_Table[]> GetDomainListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbAccessService/GetTechforDomain", ReplyAction="http://tempuri.org/IDbAccessService/GetTechforDomainResponse")]
        Tech_Forum.ServiceReference.Technology_Table[] GetTechforDomain(string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbAccessService/GetTechforDomain", ReplyAction="http://tempuri.org/IDbAccessService/GetTechforDomainResponse")]
        System.Threading.Tasks.Task<Tech_Forum.ServiceReference.Technology_Table[]> GetTechforDomainAsync(string domain);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDbAccessServiceChannel : Tech_Forum.ServiceReference.IDbAccessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DbAccessServiceClient : System.ServiceModel.ClientBase<Tech_Forum.ServiceReference.IDbAccessService>, Tech_Forum.ServiceReference.IDbAccessService {
        
        public DbAccessServiceClient() {
        }
        
        public DbAccessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DbAccessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbAccessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbAccessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public Tech_Forum.ServiceReference.Domain_Table[] GetDomainList() {
            return base.Channel.GetDomainList();
        }
        
        public System.Threading.Tasks.Task<Tech_Forum.ServiceReference.Domain_Table[]> GetDomainListAsync() {
            return base.Channel.GetDomainListAsync();
        }
        
        public Tech_Forum.ServiceReference.Technology_Table[] GetTechforDomain(string domain) {
            return base.Channel.GetTechforDomain(domain);
        }
        
        public System.Threading.Tasks.Task<Tech_Forum.ServiceReference.Technology_Table[]> GetTechforDomainAsync(string domain) {
            return base.Channel.GetTechforDomainAsync(domain);
        }
    }
}
